KTLN-437 - Extension Fields in Kotlin
Baeldung/kotlin-tutorials pull request #1039
Opened 2024-07-30 00:46 UTC by hangga

2024-09-17 18:54 UTC, theangrydev requested changes

2024-09-17 18:54 UTC, theangrydev commented on core-kotlin-modules/core-kotlin-lang-oop-4/src/test/kotlin/ExtensionFieldsAlternativesUnitTest.kt
> +    private fun String.toTitleCase(): String = this.split(" ").joinToString(" ") { it.capitalize() }
Did you apply the Baeldung formatter to the code? I'd expect to see line breaks for chained method calls

2024-09-17 18:54 UTC, theangrydev commented on core-kotlin-modules/core-kotlin-lang-oop-4/src/test/kotlin/ExtensionFieldsAlternativesUnitTest.kt
> +            set(value) { field = value }
Did you apply the Baeldung formatter to the code? I'd expect to see this on multiple lines not a single line

2024-09-20 18:07 UTC, theangrydev approved these changes

2024-09-26 08:19 UTC, hangga commented
Hi @theangrydev, need to merge.

2024-09-26 11:00 UTC, merged