Draft: noop
Baeldung/kotlin-tutorials pull request #689
Opened 2023-11-13 11:27 UTC by tapankavasthi

2023-11-23 22:05 UTC, theangrydev requested changes

2023-11-23 22:05 UTC, theangrydev commented on core-kotlin-modules/core-kotlin-date-time/src/test/kotlin/com/baeldung/timedifference/TimePeriodDifferenceUnitTest.kt
> +        assertEquals(30L, mins)
think this assertion would be clearer on the duration itself, what do you think?
```suggestion
        assertEquals(1.days + 3.hours + 30.minutes, difference)
```

2023-11-23 22:05 UTC, theangrydev commented on core-kotlin-modules/core-kotlin-date-time/src/test/kotlin/com/baeldung/timedifference/TimePeriodDifferenceUnitTest.kt
> +        val endEpochMillis: Long = 1700617692000L
It's already clear the values are Long from the L suffix
```suggestion
        val startEpochMillis = 1700617592000L
        val endEpochMillis = 1700617692000L
```

2023-11-23 22:05 UTC, theangrydev commented on core-kotlin-modules/core-kotlin-date-time/src/test/kotlin/com/baeldung/timedifference/TimePeriodDifferenceUnitTest.kt
> +        assertEquals(40L, secs)
I think this assertion would be clearer on the duration itself, what do you think?
```suggestion
        assertEquals(1.mins + 40.seconds, durationDiff)
```

2023-11-26 11:44 UTC, tapankavasthi commented on core-kotlin-modules/core-kotlin-date-time/src/test/kotlin/com/baeldung/timedifference/TimePeriodDifferenceUnitTest.kt
> +    }
I've addressed this concern while keeping the code simple to understand for the reader.

2023-11-27 00:46 UTC, theangrydev requested changes

2023-11-27 00:46 UTC, theangrydev commented on core-kotlin-modules/core-kotlin-date-time/src/test/kotlin/com/baeldung/timedifference/TimePeriodDifferenceUnitTest.kt
> +        val durationDiff = instant2.minus(instant1)
For the sake of consistency, can we name this variable `difference` too

2023-11-27 00:46 UTC, theangrydev commented on core-kotlin-modules/core-kotlin-date-time/src/test/kotlin/com/baeldung/timedifference/TimePeriodDifferenceUnitTest.kt
> +    }
Hmm. So you avoided the second `markNow()` to make the test predictable, but now it's a bit hard to understand what is being tested. How about something like this instead:
```suggestion
    @Test
    fun `given two time marks, when find difference, then give correct time difference`() {
        val timeSource = TimeSource.Monotonic
        val mark1 = timeSource.markNow()
        // call operation to measure duration of
        val mark2 = timeSource.markNow()
        val difference = mark2 - mark1
        assertThat(difference).isGreaterThanOrEqualTo(0);
    }
```

2023-11-27 22:20 UTC, theangrydev approved these changes

2023-12-04 15:54 UTC, merged