BAEL-95490 Review warnings in kotlin-build job
Baeldung/kotlin-tutorials pull request #793
Opened 2024-02-02 18:56 UTC by timis1

2024-02-13 17:21 UTC, alvin577austria requested changes
Some comments.

2024-02-13 20:24 UTC, timis1 commented on core-kotlin-modules/core-kotlin-9/src/test/kotlin/com/baeldung/underscoreoperator/UnderScoreOperator.kt
> +    var a = value
The variable a is an attribute to the class. So we cannot print a variable directly where we declare attributes.

2024-02-13 20:27 UTC, timis1 commented on core-kotlin-modules/core-kotlin-advanced-2/src/test/kotlin/com/baeldung/serialization/defaultValueParameters/DefaultValueSerializationUnitTest.kt
> +import kotlinx.serialization.*
I added as an individual import.

2024-02-13 20:29 UTC, timis1 commented on core-kotlin-modules/core-kotlin-lang-2/src/test/kotlin/com/baeldung/late/LateInitUnitTest.kt
> +import kotlin.test.*
I added as an individual import.

2024-02-13 20:30 UTC, timis1 commented on core-kotlin-modules/core-kotlin-lang/src/main/kotlin/com/baeldung/operators/Money.kt
> +import kotlinx.coroutines.newFixedThreadPoolContext
I removed that useless import

2024-02-13 20:31 UTC, timis1 commented on core-kotlin-modules/core-kotlin-lang/src/test/kotlin/com/baeldung/equalityoperators/EqualityUnitTest.kt
> +import kotlin.test.*
I added individual imports

2024-02-13 20:34 UTC, timis1 commented on pom.xml
> +						<phase>compile</phase>
Fixed the indentation

2024-02-14 21:12 UTC, alvin577austria approved these changes

2024-02-14 21:13 UTC, merged