BAEL-102141 Review warnings in kotlin-build job
Baeldung/kotlin-tutorials pull request #816
Opened 2024-02-20 18:39 UTC by timis1

2024-02-20 23:41 UTC, alvin577austria requested changes

2024-02-20 23:41 UTC, alvin577austria commented on kotlin-libraries-http/src/test/kotlin/com/baeldung/fuel/FuelHttpLiveTest.kt
> +                _, response, result ->
Can you fix the indentation here please.

2024-02-20 23:41 UTC, alvin577austria commented on kotlin-libraries-http/src/test/kotlin/com/baeldung/fuel/FuelHttpLiveTest.kt
> +                _, response, result ->
Same here.

2024-02-20 23:41 UTC, alvin577austria commented on kotlin-libraries-http/src/test/kotlin/com/baeldung/fuel/FuelHttpLiveTest.kt
> +                _, response, result ->
And here.

2024-02-20 23:41 UTC, alvin577austria commented on spring-boot-kotlin/src/main/kotlin/com/baeldung/nonblockingcoroutines/handlers/ProductsHandler.kt
> +import kotlinx.coroutines.*
Please use individual imports.

2024-02-20 23:41 UTC, alvin577austria commented on kotlin-libraries-http/src/test/kotlin/com/baeldung/fuel/FuelHttpLiveTest.kt
> +                  _, _, result ->
And here.

2024-02-21 06:59 UTC, timis1 commented on kotlin-libraries-http/src/test/kotlin/com/baeldung/fuel/FuelHttpLiveTest.kt
> +                _, response, result ->
Done

2024-02-21 06:59 UTC, timis1 commented on kotlin-libraries-http/src/test/kotlin/com/baeldung/fuel/FuelHttpLiveTest.kt
> +                _, response, result ->
Done

2024-02-21 07:00 UTC, timis1 commented on spring-boot-kotlin/src/main/kotlin/com/baeldung/nonblockingcoroutines/handlers/ProductsHandler.kt
> +import kotlinx.coroutines.*
Done

2024-02-21 07:00 UTC, timis1 commented on kotlin-libraries-http/src/test/kotlin/com/baeldung/fuel/FuelHttpLiveTest.kt
> +                  _, _, result ->
Done

2024-02-21 15:24 UTC, alvin577austria approved these changes

2024-02-21 15:24 UTC, merged